# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_movie_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=200)),
                ('cinema_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(max_length=200, default= 'test'),
            preserve_default = False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(max_length=200, default = 'test'),
            preserve_default = False,
        ),
        migrations.AddField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.Movie', default = 1),
            preserve_default= False,
        ),
        migrations.AddField(
            model_name='movie',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.Cinema', default= 1),
            preserve_default= False,
        ),
    ]
