# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_remove_movie_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='cinema_address',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_description',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='movie',
        ),
    ]
