# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_auto_20161120_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cinema_address',
            field=models.CharField(default='test', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemas.Cinema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(default='text', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default='text', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinemas.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cinema_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=2000),
        ),
    ]
