# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0010_auto_20161120_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=200),
        ),
    ]
