# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0014_screening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='times',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_description',
        ),
    ]
