# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_auto_20161106_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=20200),
            preserve_default=False,
        ),
    ]
